CREATE TABLE financial(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	description VARCHAR(255) NOT NULL,
	cash_flow_type VARCHAR(15) NOT NULL,
	month VARCHAR(10) NOT NULL,
	year INT NOT NULL,
	amount DECIMAL(6, 2) NOT NULL
)ENGINE InnoDB DEFAULT CHARSET=utf8;